# Generated by Django 4.1.7 on 2023-03-23 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='check_character_element',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-Z0-9]*$', 'Only uppercase letters and numbers allowed.')]),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='identifier_scheme_element',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z0-9]*$', 'Only uppercase letters and numbers allowed.')]),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='issuer_code_element',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[A-Z0-9]*$', 'Only uppercase letters and numbers allowed.')]),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='release_number_element',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z0-9]*$', 'Only uppercase letters and numbers allowed.')]),
        ),
    ]
