# Generated by Django 4.1.7 on 2023-03-25 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_artwork_check_character_element_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('account_type', models.CharField(choices=[(0, 'Art Creator'), (1, 'Record Label or Musician')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='check_character_element',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='identifier_scheme_element',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='issuer_code_element',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='release_number_element',
        ),
        migrations.AddField(
            model_name='artwork',
            name='GRid',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator('^[A-Z0-9]*$', 'Only uppercase letters and numbers allowed.')]),
        ),
        migrations.AddField(
            model_name='artwork',
            name='date_posted',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.creator'),
        ),
    ]
