# Generated by Django 4.1.7 on 2023-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_creator_remove_artwork_check_character_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
