# Generated by Django 4.1.7 on 2023-03-25 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_artwork_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='GRid',
        ),
        migrations.AddField(
            model_name='artwork',
            name='isrc',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(('[A-Z0-9]*$', 'Only uppercase letters and numbers are allowed for IRSC'))]),
        ),
    ]
