# Generated by Django 4.1.7 on 2023-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_artwork_grid_artwork_isrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='isrc',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
