# Generated by Django 4.1.7 on 2023-03-25 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_artwork_isrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.creator'),
        ),
    ]
