# Generated by Django 4.1.7 on 2023-03-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_artwork_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
