# Generated by Django 4.1.7 on 2023-03-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_artwork_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='account_type',
            field=models.CharField(choices=[('0', 'Art Creator'), ('1', 'Record Label or Musician')], max_length=24),
        ),
    ]
