# Generated by Django 4.1.7 on 2023-03-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_creator_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
