# Generated by Django 4.1.7 on 2023-03-28 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_artwork_image_url_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
