# Generated by Django 4.1.7 on 2023-03-28 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9188ccd-2c0f-4a9e-bf77-3ebaef1a65f5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
